studentsdb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView, TemplateView

from students.views.students import StudentUpdateView, StudentDeleteView
from students.views.groups import GroupAddView, GroupUpdateView, \
    GroupDeleteView, groups_list
from students.views.journal import JournalView
from stud_auth.views import UsersListView, UserDetailView, UserUpdateView
from registration.backends.default import views as registration_views

from .settings import MEDIA_ROOT, DEBUG


js_info_dict = {
    'packages': ('students',),
}

urlpatterns = patterns('',
    # Students urls
    url(r'^$', 'students.views.students.students_list', name='home'),
    url(r'^students/add/$', 'students.views.students.students_add',
         name='students_add'),
    url(r'^students/(?P<pk>\d+)/edit/$', StudentUpdateView.as_view(),
         name='students_edit'),
    url(r'^students/(?P<pk>\d+)/delete/$', StudentDeleteView.as_view(),
         name='students_delete'),

    # Groups urls
    url(r'^groups/$', login_required(groups_list), name='groups'),
    url(r'^groups/add/$', login_required(GroupAddView.as_view()),
         name='groups_add'),
    url(r'^groups/(?P<pk>\d+)/edit/$', login_required(GroupUpdateView.as_view()),
         name='groups_edit'),
    url(r'^groups/(?P<pk>\d+)/delete/$', login_required(GroupDeleteView.as_view()),
         name='groups_delete'),

    # Journal urls
    url(r'^journal/(?P<pk>\d+)?/?$', JournalView.as_view(), name='journal'),

    # User Related urls
    url(r'^users/profile/$', login_required(TemplateView.as_view(
        template_name='registration/profile.html')), name='profile'),
    url(r'^users/profiles/$', login_required(UsersListView.as_view()),
        name='users_list'),
    url(r'^users/profile/(?P<pk>\d+)/$', login_required(UserDetailView.as_view()),
        name='user_profile'),
    url(r'^users/profile/edit/$', login_required(UserUpdateView.as_view()),
        name='user_profile_edit'),
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'home'},
        name='auth_logout'),
    url(r'^users/register/complete/$', TemplateView.as_view(
        template_name='registration/registration_complete.html'),
        name='registration_complete'),
    url(r'^users/activate/complete/$',
        TemplateView.as_view(template_name='registration/activation_complete.html'),
        name='registration_activation_complete'),
    url(r'^users/password_reset/$', auth_views.password_reset,
        name='auth_password_reset'),
    url(r'^users/register/$', registration_views.RegistrationView.as_view(),
        name='registration_register'),
    url(r'^users/activate/(?P<activation_key>\w+)/$',
        registration_views.ActivationView.as_view(),
        name='registration_activate'),
    url(r'^users/password_reset/done/$', auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^users/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^users/reset/done/$', auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^users/password_change/$', auth_views.password_change,
        name='password_change'),
    url(r'^users/password_change/done/$',
        RedirectView.as_view(pattern_name='profile'),
        name='password_change_done'),
    url(r'^users/', include('registration.backends.default.urls', namespace='users')),
    #url(r'^users/', include('registration.backends.simple.urls',
    #    namespace='users')),

    # Social Auth Related urls
    url('^social/', include('social.apps.django_app.urls', namespace='social')),

    # Contact Admin Form
    url(r'^contact-admin/$', 'students.views.contact_admin.contact_admin',
        name='contact_admin'),

    url(r'^jsi18n\.js$', 'django.views.i18n.javascript_catalog', js_info_dict),

    # View for set language
    url('^set-language/$',
        'students.views.set_language.set_language', name='set_language'),

    url(r'^admin/', include(admin.site.urls)),

)

if DEBUG:
    # serve files from media folder
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': MEDIA_ROOT}))

students/models.py
# -*- coding: utf-8 -*-

from django.db import models

class Student(models.Model):
    """Student Model"""

    class  Meta(object):
        verbose_name = u"Студент"
        verbose_name_plural = u"Студенти"

    first_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Ім'я")

    last_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Прізвище")

    middle_name = models.CharField(
        max_length=256,
        blank=True,
        verbose_name=u"По-батькові",
        default='')

    birthday = models.DateField(
        blank=False,
        verbose_name=u"Дата народження",
        null=True)

    photo = models.ImageField(
        blank=True,
        verbose_name=u"Фото",
        null=True)

    ticket = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Білет")

    student_group = models.ForeignKey('Group',
        verbose_name=u"Група",
        blank=False,
        null=True,
        on_delete=models.PROTECT)

    notes = models.TextField(
        blank=True,
        verbose_name=u"Додаткові нотатки")

    def __unicode__(self):
        return u"%s %s" % (self.first_name, self.last_name)

class Group(models.Model):
    """Group Model"""

    class Meta(object):
        verbose_name = u"Група"
        verbose_name_plural = u"Групи"

    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Назва")

    leader = models.OneToOneField('Student',
        verbose_name=u"Староста",
        blank=True,
        null=True,
        on_delete=models.SET_NULL)

    notes = models.TextField(
        blank=True,
        verbose_name=u"Додаткові нотатки")

    def __unicode__(self):
        if self.leader:
            return u"%s (%s %s)" % (self.title, self.leader.first_name,
                 self.leader.last_name)
        else:
            return u"%s" % (self.title,)

students/models/groups.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Group(models.Model):
    """Group Model"""

    class Meta(object):
        verbose_name = _(u"Group")
        verbose_name_plural = _(u"Groups")

    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u"Title"))

    leader = models.OneToOneField(
        'Student',
        verbose_name=_(u"Leader"),
        blank=True,
        null=True,
        on_delete=models.SET_NULL)

    notes = models.TextField(
        blank=True,
        verbose_name=_(u"Extra Notes"))

    def __unicode__(self):
        if self.leader:
            return u"%s (%s %s)" % (self.title, self.leader.first_name,
                                    self.leader.last_name)
        else:
            return u"%s" % (self.title,)

students/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse

# Views for students

def students_list(request):
    students = (
        {'id': 1,
         'first_name': u'Андрій',
         'last_name': u'Вірт',
         'ticket': 2501,
         'image': 'img/student_1.jpg'},
        {'id': 2,
         'first_name': u'Юрій',
         'last_name': u'Семчук',
         'ticket': 2548,
         'image': 'img/student_2.jpg'},
        {'id': 3,
         'first_name': u'Роман',
         'last_name': u'Ярощак',
         'ticket': 2557,
         'image': 'img/student_3.jpg'},
        )
    return render(request, 'students/students_list.html',
        {'students': students})

def students_add(request):
    return HttpResponse('<h1>Student Add Form</h1>')

def students_edit(request, sid):
    return HttpResponse('<h1>Edit Student %s</h1>' % sid)

def students_delete(request, sid):
    return HttpResponse('<h1>Delete Student %s</h1>' % sid)

# Views for Groups

def groups_list(request):
    groups = (
        {'id': 1,
         'name': u'ІМЗ-21',
         'leader': {'id': 1, 'name': u'Олег Скочиляс'}},
        {'id': 2,
         'name': u'ІМЗ-22',
         'leader': {'id': 2, 'name': u'Софія Михайлів'}},
    )
    return render(request, 'students/groups_list.html',
         {'groups': groups})

def groups_add(request):
    return HttpResponse('<h1>Group Add Form</h1>')

def groups_edit(request, gid):
    return HttpResponse('<h1>Edit Group %s</h1>' % gid)

def groups_delete(request, gid):
    return HttpResponse('<h1>Delete Group %s</h1>' % gid)

students/views/contact_admin.py
import logging

from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import permission_required, login_required

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from studentsdb.settings import ADMIN_EMAIL


class ContactForm(forms.Form):

    def __init__(self, *args, **kwargs):
        # call original initializator
        super(ContactForm, self).__init__(*args, **kwargs)

        # this helper object allows us to customize form
        self.helper = FormHelper()

        # form tag attributes
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('contact_admin')

        # twitter bootstrap styles
        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'

        # form buttons
        self.helper.add_input(Submit('send_button', _(u'Send')))

    from_email = forms.EmailField(
        label=_(u"Your Email Address"))

    subject = forms.CharField(
        label=_(u"Email Subject"),
        max_length=128)

    message = forms.CharField(
        label=_(u"Email Body"),
        widget=forms.Textarea)

@login_required
def contact_admin(request):
    # check if form was posted
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)

        # check whether user data is valid:
        if form.is_valid():
            # send email
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email = form.cleaned_data['from_email']

            try:
                send_mail(subject, message, from_email, [ADMIN_EMAIL])
            except Exception:
                message = _(u"An error occured during email transfer. Please, "
                    "try again later.")
                logger = logging.getLogger(__name__)
                logger.exception(message)
            else:
                message = _(u"Message sent successfully!")

            # redirect to same contact page with success message
            return HttpResponseRedirect(
                u'%s?status_message=%s' % (reverse('contact_admin'), message))

    # if there was not POST render blank form
    else:
        form = ContactForm()

    return render(request, 'contact_admin/form.html', {'form': form})

students/views/groups.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.forms import ModelForm, ValidationError
from django.views.generic import CreateView, UpdateView, DeleteView
from django.utils.translation import ugettext as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import FormActions

from ..models import Group
from ..util import paginate, get_current_group, DispatchLoginRequired

def groups_list(request):
    """Returns page with list of groups."""
    # check if we need to show only one group of students
    current_group = get_current_group(request)
    if current_group:
        groups = Group.objects.filter(id=current_group.id)
    else:
        # otherwise show all groups
        groups = Group.objects.all()

    # try to order groups list
    order_by = request.GET.get('order_by', '')
    if order_by in ('title', 'leader'):
        groups = groups.order_by(order_by)
        if request.GET.get('reverse', '') == '1':
            groups = groups.reverse()
    else:
        order_by = 'title'
        groups = groups.order_by(order_by)

    # paginate groups
    paginator = Paginator(groups, 3)
    page = request.GET.get('page')
    try:
        groups = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer, deliver first page.
        groups = paginator.page(1)
    except EmptyPage:
        # if page is out of range (e.g. 9999), deliver last page of results.
        groups = paginator.page(paginator.num_pages)
    return render(request, 'students/groups_list.html',
                  {'groups': groups})

class GroupForm(ModelForm):
    class Meta:
        model = Group

    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        # add form or edit form
        if kwargs['instance'] is None:
            add_form = True
        else:
            add_form = False

        # set form tag attributes
        if add_form:
            self.helper.form_action = reverse('groups_add')
        else:
            self.helper.form_action = reverse('groups_edit',
                kwargs={'pk': kwargs['instance'].id})
        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'

        # set form field properties
        self.helper.help_text_inline = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'

        # add buttons
        if add_form:
            submit = Submit('add_button', _(u"Add"),
                            css_class="btn btn-primary")
        else:
            submit = Submit('save_button', _(u"Save"),
                            css_class="btn btn-primary")
        self.helper.layout[-1] = FormActions(
            submit,
            Submit('cancel_button', _(u"Cancel"), css_class="btn btn-link"),
        )

        self.fields['leader'].queryset =\
             self.instance.student_set.order_by('last_name')

    def clean_leader(self):
        """ Check if leader is in the same group """
        new_leader = self.cleaned_data['leader']
        if hasattr(new_leader, 'student_group') and new_leader.student_group != self.instance:
            raise ValidationError(_(u"Student is not in this group!"),
                                   code='invalid')
        return new_leader

class BaseGroupFormView(object):

    def get_success_url(self):
        return u'%s?status_message=%s' % (reverse('groups'),
                                          _(u"Changes saved successfully!"))

    def post(self, request, *args, **kwargs):
        # handle cancel button
        if request.POST.get('cancel_button'):
            return HttpResponseRedirect(reverse('groups') +
                u'?status_message=%s' % _(u"Changes canceled."))
        else:
            return super(BaseGroupFormView, self).post(
                request, *args, **kwargs)

class GroupAddView(DispatchLoginRequired, BaseGroupFormView, CreateView):
    model = Group
    form_class = GroupForm
    template_name = 'students/groups_form.html'

class GroupUpdateView(DispatchLoginRequired, BaseGroupFormView, UpdateView):
    model = Group
    form_class = GroupForm
    template_name = 'students/groups_form.html'

class GroupDeleteView(DispatchLoginRequired, BaseGroupFormView, DeleteView):
    model = Group
    template_name = 'students/groups_confirm_delete.html'

students/views/set_language.py
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.urlresolvers import reverse


def set_language(request):
    if request.method == "POST":
        # get path refferer
        return_path = request.POST.get('return-path', reverse('home'))
        response = HttpResponseRedirect(return_path)
        # get lang_code of selected language
        selected_language = request.POST.get('lang', settings.LANGUAGE_CODE)
        # set cookie
        max_age = 365*24*60*60 # year
        response.set_cookie(
            settings.LANGUAGE_COOKIE_NAME,
            selected_language,
            max_age=max_age)
        return response

students/templates/students/base.html
{% load i18n %}
{% load static from staticfiles %}
{% load select_menu %}
<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8"/>
  <title>{% trans "Students Accounting Service" %} - {% block meta_title %}{% endblock meta_title %}</title>
  <meta name="description" value="{% trans "App to manage students database" %}"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
  <link rel="stylesheet"
        href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/css/bootstrap-datetimepicker.min.css">
  <link rel="stylesheet"
        href="{{ PORTAL_URL }}{% static "css/main.css" %}">

  {% block extra_css %}{% endblock extra_css %}

</head>
<body>

  <!-- Start Container -->
  <div class="container">

    <!-- Start Header -->
    <div class="row" id="header">
      {% block logo %}
      <div class="col-xs-6">
        <h1>{% trans "Students Accounting Service" %}</h1>
      </div>
      {% endblock logo %}
      <!-- Language Select -->
      <div class="col-xs-1" id='lang-select'>
        <div class='lang-select-form'>
          <form action="{% url "set_language" %}" method='post'>{% csrf_token %}
            <input type='hidden' name='lang' value='uk'>
            <input type='hidden' name='return-path' value='{{request.path}}'>
            <button type='submit' class='btn btn-link'>Укр</button>
          </form>
        </div>
        <div class='lang-select-form'>
          <form action="{% url "set_language" %}" method='post'>{% csrf_token %}
            <input type='hidden' name='lang' value='en'>
            <input type='hidden' name='return-path' value='{{request.path}}'>
            <button type='submit' class='btn btn-link'>Eng</button>
          </form>
        </div>
      </div>
      <!-- End Language Select -->
      {% block groups_selector %}
      {% if user.is_authenticated %}
      <div class="col-xs-4" id="group-selector">
        <strong>{% trans "Group" %}:</strong>
        <select>
          <option value="">{% trans "All Students" %}</option>
          {% for group in GROUPS %}
          <option value="{{ group.id }}"{% if group.selected %}selected="1"{% endif %}>{{ group.title }}{% if group.leader %}, {{ group.leader }}{% endif %}</option>
          {% endfor %}
        </select>
      </div>
      <!-- User's toolbar for authenticated users -->
      <div class="col-xs-6" id="user-toolbar">
        <a href="{% url "profile" %}">{{ user.get_full_name|default:user.username }}</a> |
        <a href="{% url "users:auth_logout" %}">{% trans "Logout" %}</a>
      </div>
      {% else %}
      <!-- User's toolbar for anonymous users -->
      <div class="col-xs-6" id="user-toolbar">
        <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">{% trans "via Facebook" %}</a> |
        <a href="{% url "users:auth_login" %}">{% trans "Log in" %}</a> |
        <a href="{% url "users:registration_register" %}">{% trans "Register" %}</a>
      </div>
      {% endif %}
      {% endblock groups_selector %}
    </div>
    <!-- End Header -->

    <!-- Start SubHeader -->
    <div class="row" id="sub-header">
      <div class="col-xs-12">
        {% url 'home' as home_page %}
        {% url 'journal' as journal_page %}
        {% url 'groups' as groups_page %}
        {% url 'users_list' as users_page %}
        {% url 'contact_admin' as contact_admin %}
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" {% select_menu 'home' %}><a href="{{ home_page }}">{% trans "Students" %}</a></li>
          {% if user.is_authenticated %}
          <li role="presentation" {% select_menu 'journal' %}><a href="{{ journal_page }}">{% trans "Journal" %}</a></li>
          <li role="presentation" {% select_menu 'groups' %}><a href="{{ groups_page }}">{% trans "Groups" %}</a></li>
          <li role="presentation" {% select_menu 'users_list' %}><a href="{{ users_page }}">{% trans "Users" %}</a></li>
          <li role="presentation" {% select_menu 'contact_admin' %}><a href="{{ contact_admin }}">{% trans "Contact" %}</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
    <!-- End SubHeader -->

    <!-- Start Content Columns -->
    <div class="row" id="content-columns">
      <div class="col-xs-12" id="content-column">

        {% block status_message %}
        {% if request.GET.status_message %}
        <div class="alert alert-warning" role="alert">{{ request.GET.status_message }}</div>
        {% endif %}
        {% endblock %}

        <h2>{% block title %}{% endblock title %}</h2>
        {% block content %}{% endblock content %}

      </div>
    </div>
    <!-- End Content Columns -->

    <!-- Start Footer -->
    {% block footer %}
    <div class="row" id="footer">
      <div class="col-xs-12">
        &copy; 2019 {% trans "Students Accounting Service" %}
      </div>
    </div>
    {% endblock footer %}
    <!-- End Footer -->

  </div>
  <!-- End Container -->

  <!-- Modal Boilerplate -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
       aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel"><!-- --></h4>
        </div>
        <div class="modal-body"><!-- --></div>
        <div class="modal-footer"><!-- --></div>
      </div>
    </div>
  </div>

  <!-- Javascripts Inclusion -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
  <script src="{% static "js/jquery.cookie.js" %}"></script>
  <script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/js/bootstrap-datetimepicker.min.js"></script>
  <script type="text/javascript" src="{% url 'django.views.i18n.javascript_catalog' %}"></script>
  <script src="{% static "js/main.js" %}"></script>
  {% block extra_js %}{% endblock extra_js %}
</body>
</html>

students/templates/students/groups_confirm_delete.html
{% extends "students/base.html" %}

{% load i18n %}
{% load static from staticfiles %}

{% block meta_title %}{% trans "Delete Group" %}{% endblock meta_title %}

{% block title %}{% trans "Delete Group" %}{% endblock title %}

{% block content %}

<form action="{% url "groups_delete" object.id %}" method="post">
  {% csrf_token %}
  <p>{% blocktrans %}Do you really want to delete group: "{{ object }}"?{% endblocktrans %}</p>
  <input type="submit" value="{% trans "Yes" %}" name="delete_button"
         class="btn btn-danger" /><br /><br />
  <a href="{% url "groups" %}" class="btn btn-info">{% trans "No" %}</a><br /><br />
</form>

{% endblock content %}

students/templates/students/groups_edit.html
{% extends "students/base.html" %}

{% load i18n %}

{% load static from staticfiles %}

{% load crispy_forms_tags %}

{% block meta_title %}{% trans "Edit Group" %}{% endblock meta_title %}

{% block title %}{% trans "Edit Group" %}{% endblock title %}

{% block status_message %}

{% if form.errors %}
<div class="alert alert-warning" role="alert">{% trans "Please, check the errors" %}</div>
{% endif %}
{% endblock %}

{% block content %}

{% crispy form %}

{% endblock content %}

students/templates/students/groups_form.html
{% extends "students/base.html" %}

{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block meta_title %}{% trans "Group Form" %}{% endblock meta_title %}

{% block title %}{% trans "Group Form" %}{% endblock title %}

{% block status_message %}
{% if form.errors %}
<div class="alert alert-warning" role="alert">{% trans "Please, correct the following errors." %}</div>
{% endif %}
{% endblock %}

{% block content %}

{% crispy form %}

{% endblock content %}

students/templates/students/groups_list.html
{% extends "students/base.html" %}

{% load i18n %}

{% load static from staticfiles %}

{% block meta_title %}{% trans "Groups List" %}{% endblock meta_title %}

{% block title %}{% trans "Groups List" %}{% endblock title %}

{% block content %}

{% if perms.students.add_student %}
<a href="{% url "groups_add" %}" class="btn btn-primary">{% trans "Add Group" %}</a>
{% endif %}

<!-- Start Groups Listing -->
<table class="table table-hover table-striped">
  {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
  <thead>
    <tr>
      <th>#</th>
      <th>
        <a href="{% url "groups" %}?order_by=title{% if reverse != '1' %}&amp;reverse=1{% endif %}">
          {% trans "Title" %}
          {% if not order_by %}&uarr;
          {% elif order_by == 'title' and reverse != '1' %}&uarr;
          {% elif order_by == 'title' and reverse == '1' %}&darr;
          {% endif %}
        </a>
      </th>
      <th>
        <a href="{% url "groups" %}?order_by=leader{% if reverse != '1' %}&amp;reverse=1{% endif %}">
          {% trans "Leader" %}
          {% if order_by == 'leader' and reverse != '1' %}&darr;
          {% elif order_by == 'leader' and reverse == '1' %}&uarr;
          {% endif %}
        </a>
      </th>
      {% if user.is_authenticated %}
      <th>{% trans "Actions" %}</th>
      {% endif %}      
    </tr>
  </thead>
  {% endwith %}
  <tbody>
    {% for group in groups %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td><a href="{% url "groups_edit" group.id %}">{{ group.title }}</a></td>
      <td><a href="{% url "groups_edit" group.id %}">{{ group.leader }}</a></td>
      {% if user.is_authenticated %}
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle"
                  data-toggle="dropdown">{% trans "Actions" %}
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url "groups_edit" group.id %}">{% trans "Edit" %}</a></li>
            <li><a href="{% url "groups_delete" group.id %}">{% trans "Delete" %}</a></li>
          </ul>
        </div>
      </td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
<!-- End Groups Listing -->

{% if groups.has_other_pages %}
{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
<nav>
  <ul class="pagination">
    <li>
      <a href="{% url "groups" %}?page=1&amp;order_by={{ order_by }}&amp;reverse={{ reverse }}">&laquo;</a>
    </li>
    {% for p in groups.paginator.page_range %}
    <li {% if groups.number == p %}class='active'{% endif %}>
        <a href="{% url "groups" %}?page={{ p }}&amp;order_by={{ order_by }}&amp;reverse={{ reverse }}">{{ p }}</a>
    </li>
    {% endfor %}
    <li>
        <a href="{% url "groups" %}?page={{ groups.paginator.num_pages }}&amp;order_by={{ order_by }}&amp;reverse={{ reverse }}">
        &raquo;</a>
    </li>
    </ul>
</nav>
{% endwith %}
{% endif %}

{% endblock content %}

students/templates/students/students_edit.html
{% extends "students/base.html" %}

{% load i18n %}

{% load static from staticfiles %}

{% load crispy_forms_tags %}

{% block meta_title %}{% trans "Edit Student" %}{% endblock meta_title %}

{% block title %}{% trans "Edit Student" %}{% endblock title %}

{% block status_message %}
{% if form.errors %}
<div class="alert alert-warning" role="alert">{% trans "Please, correct the following errors." %}</div>
{% endif %}
{% endblock status_message %}

{% block content %}

{% crispy form %}

{% endblock content %}